"""
Defines the shared state schema for the LangGraph orchestrator.
This file represents the data contract passed between various nodes.
"""

import operator
from typing import Annotated, Optional, TypedDict

import numpy as np

from src.orchestrator.agents.base import AgentSummary


class PatientState(TypedDict):
    """
    Represents the complete state of a patient during the
    Multi-Agent System execution.
    """

    # Unique patient identifier (e.g., TCGA-XX-XXXX)
    patient_id: str

    # Cohort identifier (luad or lusc)
    cohort: str

    # Raw feature arrays for each modality (None if missing)
    clinical: Optional[np.ndarray]
    transcriptomics: Optional[np.ndarray]
    wsi: Optional[np.ndarray]
    methylation: Optional[np.ndarray]

    # Modality availability (populated by DataLoader)
    available_modalities: list[str]
    missing_modalities: list[str]

    # Optional override: force specific modalities to be treated as missing.
    forced_missing_modalities: list[str]

    # Summaries from modality understanding agents (Phase 4)
    agent_summaries: dict[str, AgentSummary]

    # Mining rules produced by the Miner node (AFM2).
    mining_rules: dict[str, str]

    # Refined guidance produced by the pre-generation Verifier (one entry per
    # missing modality). Conditions the Generator's retrieval strategy.
    guidance: dict[str, str]

    # N candidate arrays per missing modality, populated by the Generator.
    # The post-generation Verifier scores each and promotes the best to
    # generated_modalities.
    generation_candidates: dict

    # Features generated by the Generator node
    generated_modalities: dict[str, np.ndarray]

    # Output from the Verifier node
    verification_scores: dict[str, float]
    verification_passed: bool

    # Final survival prediction output
    survival_prediction: Optional[float]

    # --- Predictor outputs ---
    # Risk class derived from training tertiles ('low' | 'medium' | 'high' | 'unknown').
    risk_class: str
    # Top-K SHAP features for this patient: list of (feature_name, abs_importance).
    top_shap_features: list
    # SHAP details with per-feature value context for reporting.
    shap_feature_details: list
    # Per-modality data provenance: real / generated / zero, with metadata.
    # Consumed by the Language Agent for the clinical report's caveats section.
    source_map: dict

    # Post-hoc uncertainty flag.  Dict with three keys:
    #   provenance_proportion    float [0,1]
    #   mahalanobis_ood_distance {"distance", "percentile_rank", "backend"}
    #   bootstrap_ci_risk_score  {"lower", "point", "upper"}
    prediction_reliability: dict

    # --- Language Agent I/O ---
    # Free-text query from the user (set by run.py CLI from --query).
    user_query: str
    # Structured parse of user_query: {"patient_id": str, "cohort": str|None}.
    # Populated by the LanguageAgent entry node.
    parsed_query: dict
    # Final markdown clinical report. Populated by the LanguageAgent exit node.
    clinical_report: str

    # Execution metadata
    routing_decision: str

    # Execution log: uses operator.add to concatenate
    execution_log: Annotated[list[str], operator.add]

    # Feedback from Verifier to guide Generator during self-refinement
    correction_hints: dict[str, str]
