"""
Defines the shared state schema for the LangGraph orchestrator.
This file represents the data contract passed between various nodes (Data Loader, Router, Generator, Verifier, Predictor).
"""

import operator
from typing import Annotated, Optional, TypedDict

import numpy as np


class PatientState(TypedDict):
    """
    Represents the complete state of a patient during the Multi-Agent System execution.
    """

    # Unique patient identifier (e.g., TCGA-XX-XXXX)
    patient_id: str

    # Raw feature arrays for each modality (None if the modality is missing)
    clinical: Optional[np.ndarray]
    transcriptomics: Optional[np.ndarray]
    wsi: Optional[np.ndarray]
    methylation: Optional[np.ndarray]

    # Modality availability (initially populated by the Data Loader)
    available_modalities: list[str]
    missing_modalities: list[str]

    # Mining rules produced by the Miner node (AFM2).
    # Keys are missing modality names, values are the rule strings
    # that guide the Generator on how to reconstruct each modality.
    mining_rules: dict[str, str]

    # Features generated by the AI for missing modalities (Generator node)
    # Keys are modality names, values are the imputed arrays
    generated_modalities: dict[str, np.ndarray]

    # Output from the Verifier node (checks the quality of generated data)
    verification_scores: dict[str, float]
    verification_passed: bool

    # Final survival prediction output (ML Baseline node)
    survival_prediction: Optional[float]

    # Execution metadata for clinical interpretability and debugging
    routing_decision: str

    # Execution log: uses operator.add to concatenate logs from various nodes instead of overwriting them at each step.
    execution_log: Annotated[list[str], operator.add]
    correction_hints: dict[str, str]
